POST http://localhost:4000/patients
Content-Type: application/json

{
  "name" : "Saquib Zarjis Ansari",
  "email" : "kafffckssaff_tesgt@gmail.com",
  "address" : "angus",
  "dateOfBirth" : "2004-01-04",
  "registeredDate" : "2004-01-04"
}